### ISSUE TITLE
problem with the build

### ISSUE THREAD

**Issue by Disarray1** [gabek/vadeo#8]
Hi, 

Im trying to run vadeo on my arm64 but its giving me this strange error everytime.
Must be a build error from my side.
Its making a config.yaml dir instead of a file.
Im did  : docker build -t vadeo .
Can you help me with it?

it runs but it can't read the config.yaml file.

- goroutine 20 [running]:
- main.streamAudio(0x40000ace20)
- 	/build/main.go:51 +0x204
- created by main.start
- 	/build/main.go:74 +0x2a0
- config file err read config.yaml: is a directory

**Comment by gabek** [comment]
The error says your `config.yaml` is actually a directory. Do you have a real `config.yaml` file?

**Comment by Disarray1** [comment]
I deleted the config.yaml directory and replaced it with a config.yaml file.
Problem  is, it  automatically changing back to a directory.

**Comment by gabek** [comment]
Are you sure this is a problem with Vadeo and not how you're using Docker? Vadeo doesn't create directories. Please try it outside of Docker and track down where your issues are, it sounds like you're using Docker mounts incorrectly.

**Comment by Disarray1** [comment]
![install](https://user-images.githubusercontent.com/128985488/227805708-4f3dac17-3d2d-4bdf-bde1-ddb8ae221e58.jpg)

**Comment by Disarray1** [comment]
ok gone try installing tommorow outside docker

I see in docker inspect that i missing some mounts to config.yaml and the logo & background.
instead he mounted :
 "Mounts": [
            {
                "Type": "bind",
                "Source": "/docker/owncast/data",
                "Destination": "/app/data",
                "Mode": "",
                "RW": true,
                "Propagation": "rprivate"

**Comment by Disarray1** [comment]
I will check it later. thxs

**Comment by Disarray1** [comment]
is this error because my system is linux/arm64/v8 and not v7.

Removing intermediate container d58d9465052c
 ---> 9b3a7b3fc0cb
Step 6/12 : FROM jrottenberg/ffmpeg:4.1-alpine
4.1-alpine: Pulling from jrottenberg/ffmpeg
72cfd02ff4d0: Pull complete
387d5d36a1d2: Pull complete
364a040390ad: Pull complete
Digest: sha256:0c4f4038d2e7fd47bc69023467d633dd00c60ba3745816dae0f09f124e2bbddf
Status: Downloaded newer image for jrottenberg/ffmpeg:4.1-alpine
 ---> 213ac786ebf1
Step 7/12 : COPY --from=builder /build/vadeo /app/
 ---> 0612fd951db6
Step 8/12 : COPY --from=builder /build/logo.png /app/
 ---> f3c84caf0c48
Step 9/12 : COPY --from=builder /build/polentical-neon.ttf /app/
 ---> f792aa47f39a
Step 10/12 : COPY --from=builder /build/background.mp4 /app/
 ---> 30af6a3ecfb7
Step 11/12 : WORKDIR /app
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in d2e956b70f19
Removing intermediate container d2e956b70f19
 ---> 17a6e72721e0
Step 12/12 : ENTRYPOINT ["./vadeo"]
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 7a839808124a
Removing intermediate container 7a839808124a
 ---> f9a97c3dc502
Successfully built f9a97c3dc502
Successfully tagged vadeo:latest

**Comment by gabek** [comment]
It says `---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested` in your log.

**Comment by Disarray1** [comment]
Hi,

Can I do something to fix it? 

vadeo_0.2.0_linux_armv7.tar.gz. That one works when I start it
I did sudo apt install -y ffmpeg  But log.txt says: ffmpeg: not found.
So it doesnt start.

**Comment by Disarray1** [comment]
can you help me? The binary vadeo can't find ffmpeg.
Its installed but log says: ffmpeg not found.

**Comment by gabek** [comment]
How and where was ffmpeg installed?

**Comment by Disarray1** [comment]
Dunno where its installed I did sudo apt install -y ffmpeg

whereis ffmpeg
ffmpeg: /usr/bin/ffmpeg /usr/share/ffmpeg /usr/share/man/man1/ffmpeg.1.gz

**Comment by Disarray1** [comment]
ok strange, tryed it again and now it works. Thanks man
